# Generated by Django 4.2.5 on 2024-01-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_alter_historicalinterface_wait_action_and_more'),
        ('classapp', '0002_remove_class_id_remove_historicalclass_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='InterfaceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.interface'),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='InterfaceId',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='interface.interface'),
        ),
    ]
