# Generated by Django 4.2.5 on 2024-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_alter_class_interfaceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='IgnoreOnIngest',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='IgnoreOnIngest',
            field=models.BooleanField(),
        ),
    ]
