# Generated by Django 4.2.5 on 2024-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_alter_class_ignoreoningest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='IgnoreOnIngest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalclass',
            name='IgnoreOnIngest',
            field=models.BooleanField(default=False),
        ),
    ]
