# Generated by Django 4.2.5 on 2024-02-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_alter_historicalinterface_wait_action_and_more'),
        ('classapp', '0005_alter_class_ignoreoningest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='InterfaceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.interface'),
        ),
    ]
