# Generated by Django 4.2.5 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_alter_class_interfaceid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('InterfaceId', 'Name'), name='unique_class_name_in_interface'),
        ),
    ]
