# Generated by Django 4.2.5 on 2024-01-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='code',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
