# Generated by Django 4.2.5 on 2024-01-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_interfaceid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='precedingcollectionid',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='precedingcollectionid',
        ),
    ]
