# Generated by Django 4.2.5 on 2024-02-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_alter_interface_connection_id_and_more'),
        ('collection', '0005_alter_collection_executiontriggerrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='interfaceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.interface'),
        ),
    ]
