# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_collection_interfaceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='executiontriggerrule',
            field=models.SmallIntegerField(choices=[(1, '1 - Success'), (2, '2 - Complete')]),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='executiontriggerrule',
            field=models.SmallIntegerField(choices=[(1, '1 - Success'), (2, '2 - Complete')]),
        ),
    ]
