# Generated by Django 4.2.5 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_collection_executiontriggerrule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('interfaceid', 'name'), name='unique_collection_name_in_interface'),
        ),
    ]
