# Generated by Django 4.2.5 on 2024-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_interfacetype_interfacedependence_interfacecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='interface_category_id',
            new_name='interface_category',
        ),
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='interface_type_id',
            new_name='interface_type',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_category_id',
            new_name='interface_category',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_type_id',
            new_name='interface_type',
        ),
        migrations.RemoveField(
            model_name='historicalinterface',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicalinterface',
            name='code',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
