# Generated by Django 4.2.5 on 2024-01-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_rename_interface_category_id_historicalinterface_interface_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='interface_category',
            new_name='interface_category_id',
        ),
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='interface_type',
            new_name='interface_type_id',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_category',
            new_name='interface_category_id',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_type',
            new_name='interface_type_id',
        ),
    ]
