# Generated by Django 4.2.5 on 2024-01-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_rename_interface_category_historicalinterface_interface_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacecategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interfacedependence',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interfacetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='interfacecategory',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interfacedependence',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
