# Generated by Django 4.2.5 on 2024-01-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_connection_created_datetime_and_more'),
        ('schedule', '0001_initial'),
        ('interface', '0005_remove_interfacecategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterface',
            name='connection_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='connection.connection'),
        ),
        migrations.AlterField(
            model_name='historicalinterface',
            name='schedule_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='connection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.connection'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
