# Generated by Django 4.2.5 on 2024-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_historicalinterface_connection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='active_end_date',
            new_name='active_end_date_test',
        ),
        migrations.RenameField(
            model_name='historicalinterface',
            old_name='active_start_date',
            new_name='active_start_date_test',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='active_end_date',
            new_name='active_end_date_test',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='active_start_date',
            new_name='active_start_date_test',
        ),
    ]
