# Generated by Django 4.2.5 on 2024-01-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_historicalinterface_active_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinterface',
            name='active_end_date_test',
        ),
        migrations.RemoveField(
            model_name='historicalinterface',
            name='active_start_date_test',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='active_end_date_test',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='active_start_date_test',
        ),
    ]
