# Generated by Django 4.2.5 on 2024-02-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_historicalschedule_frequency_and_more'),
        ('connection', '0003_remove_connection_id_remove_historicalconnection_id_and_more'),
        ('interface', '0010_alter_historicalinterface_wait_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='connection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connection.connection'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.interfacecategory'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.interfacetype'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='interfacedependence',
            name='dependent_on_interface',
            field=models.ForeignKey(db_column='DependentOnInterfaceId', on_delete=django.db.models.deletion.PROTECT, related_name='dependent_interface', to='interface.interface'),
        ),
        migrations.AlterField(
            model_name='interfacedependence',
            name='interface_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interface.interface'),
        ),
    ]
