# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_alter_interface_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterface',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='interfacecategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
