# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_remove_loadpattern_id_alter_loadpattern_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadpattern',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
