# Generated by Django 4.2.5 on 2024-01-11 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Code', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=128)),
                ('Frequency', models.IntegerField()),
                ('FrequencyInterval', models.IntegerField()),
                ('FrequencyRelativeInterval', models.IntegerField()),
                ('FrequencyRecurrenceFactor', models.IntegerField()),
                ('FrequencySubDayType', models.IntegerField()),
                ('FrequencySubDayInterval', models.IntegerField()),
                ('ActiveStartDate', models.IntegerField()),
                ('ActiveEndDate', models.IntegerField()),
                ('ActiveStartTime', models.IntegerField()),
                ('ActiveEndTime', models.IntegerField()),
                ('IsEnabled', models.BooleanField(max_length=1)),
                ('Version', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('skip_save', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(max_length=128)),
                ('Frequency', models.IntegerField()),
                ('FrequencyInterval', models.IntegerField()),
                ('FrequencyRelativeInterval', models.IntegerField()),
                ('FrequencyRecurrenceFactor', models.IntegerField()),
                ('FrequencySubDayType', models.IntegerField()),
                ('FrequencySubDayInterval', models.IntegerField()),
                ('ActiveStartDate', models.IntegerField()),
                ('ActiveEndDate', models.IntegerField()),
                ('ActiveStartTime', models.IntegerField()),
                ('ActiveEndTime', models.IntegerField()),
                ('IsEnabled', models.BooleanField(max_length=1)),
                ('Version', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical schedule',
                'verbose_name_plural': 'historical schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
