# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_historicalschedule_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='Frequency',
            field=models.IntegerField(choices=[(0, '0 - Once'), (1, '1 - Daily'), (2, '2 - Weekly'), (3, '3 - Monthly'), (4, '4 - Monthly-Relative')]),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='FrequencyRelativeInterval',
            field=models.IntegerField(choices=[(0, '0 - Unused'), (1, '1 - First'), (2, '2 - Second'), (3, '3 - Third'), (4, '4 - Fourth'), (5, '5 - Last')]),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='FrequencySubDayType',
            field=models.IntegerField(choices=[(1, '1 - Minutes'), (2, '2 - Hourly')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Frequency',
            field=models.IntegerField(choices=[(0, '0 - Once'), (1, '1 - Daily'), (2, '2 - Weekly'), (3, '3 - Monthly'), (4, '4 - Monthly-Relative')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='FrequencyRelativeInterval',
            field=models.IntegerField(choices=[(0, '0 - Unused'), (1, '1 - First'), (2, '2 - Second'), (3, '3 - Third'), (4, '4 - Fourth'), (5, '5 - Last')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='FrequencySubDayType',
            field=models.IntegerField(choices=[(1, '1 - Minutes'), (2, '2 - Hourly')]),
        ),
    ]
