# Generated by Django 4.2.5 on 2024-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_historicalschedule_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='Name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
