# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_remove_role_id_alter_role_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'ad_group_name')},
        ),
    ]
