# Generated by Django 4.2.5 on 2024-03-26 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processstatus', '0002_remove_statusupcoming_id_alter_statusupcoming_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='processstatus',
            new_name='StatusProcess',
        ),
        migrations.AlterModelTable(
            name='statusprocess',
            table='StatusProcess',
        ),
    ]
