# Generated by Django 4.2.5 on 2024-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processstatus', '0003_rename_processstatus_statusprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusprocess',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
