# Generated by Django 4.2.5 on 2024-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='PipelineName',
            new_name='ProcessName',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='PipelineParameters',
            new_name='ProcessParameters',
        ),
        migrations.RenameField(
            model_name='historicaltask',
            old_name='SubPipelineParameters',
            new_name='SubProcessParameters',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='PipelineName',
            new_name='ProcessName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='PipelineParameters',
            new_name='ProcessParameters',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='SubPipelineParameters',
            new_name='SubProcessParameters',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='Code',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='DeduplicateSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='Code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='DeduplicateSource',
            field=models.BooleanField(default=False),
        ),
    ]
