# Generated by Django 4.2.5 on 2024-02-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_remove_loadpattern_id_alter_loadpattern_code'),
        ('collection', '0005_alter_collection_executiontriggerrule_and_more'),
        ('classapp', '0006_alter_class_interfaceid'),
        ('Task', '0002_rename_pipelinename_historicaltask_processname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classapp.class'),
        ),
        migrations.AlterField(
            model_name='task',
            name='CollectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='task',
            name='LoadPatternId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pattern.loadpattern'),
        ),
    ]
