# Generated by Django 4.2.5 on 2024-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_classid_alter_task_collectionid_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('CollectionId', 'Name'), name='unique_task_name_in_collection'),
        ),
    ]
