# Generated by Django 4.2.5 on 2024-02-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_alter_class_ignoreoningest_and_more'),
        ('attribute', '0005_alter_attribute_ignore_on_ingest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classapp.class'),
        ),
    ]
