# Generated by Django 4.2.5 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_alter_attribute_class_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={},
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('class_id', 'target_name'), name='unique_target_name_in_class'),
        ),
    ]
