# Generated by Django 4.2.5 on 2023-09-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('entity_table_name', models.CharField(max_length=250)),
                ('entity_key_column', models.CharField(max_length=250)),
                ('entity_name_column', models.CharField(max_length=250)),
                ('entity_other_attributes', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
