# Generated by Django 4.2.5 on 2023-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_rename_report_id_entity_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
