# Generated by Django 4.2.5 on 2024-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_connection_created_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalconnection',
            name='id',
        ),
        migrations.AlterField(
            model_name='connection',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalconnection',
            name='code',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
