# Generated by Django 4.2.5 on 2024-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_remove_connection_id_remove_historicalconnection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalconnection',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
