# Generated by Django 4.2.5 on 2023-10-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIIngestionBatchStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_load_dt', models.DateTimeField()),
                ('meta_run_step_log_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=200, null=True)),
                ('batch_id', models.IntegerField()),
                ('batch_filter', models.TextField(null=True)),
                ('batch_stg_file_add_field_value', models.TextField(null=True)),
                ('api_extract_status_id', models.IntegerField(null=True)),
                ('api_extract_run_start_dt', models.DateTimeField(null=True)),
                ('api_extract_run_end_dt', models.DateTimeField(null=True)),
                ('api_extract_error_message', models.TextField(null=True)),
                ('convert_json_to_stg_file_has_error', models.BooleanField(null=True)),
                ('convert_json_to_stg_file_error_message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'APIIngestionBatchStatusLog',
            },
        ),
    ]
