# Generated by Django 4.2.5 on 2023-12-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_apiingestionbatchstatuslog_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('interface_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('task_load_date', models.DateTimeField()),
                ('activity_name', models.CharField(max_length=128)),
                ('activity_status', models.CharField(max_length=50)),
                ('activity_run_start_time', models.DateTimeField()),
                ('activity_run_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CheckpointLog',
            },
        ),
    ]
