# Generated by Django 4.2.5 on 2023-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_checkpointlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('run_step_log_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=128)),
                ('stage_row_count', models.IntegerField(null=True)),
                ('insert_row_count', models.IntegerField(null=True)),
                ('update_row_count', models.IntegerField(null=True)),
                ('delete_row_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
