# Generated by Django 4.2.5 on 2023-12-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('interface', '0002_interfacetype_interfacedependence_interfacecategory_and_more'),
        ('logs', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('StatusId', models.IntegerField()),
                ('execution_date', models.DateTimeField()),
                ('run_type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rerun', models.CharField(max_length=1)),
                ('time_to_live', models.DateTimeField()),
                ('interface_pipeline_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduler_pipeline_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('InterfaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.interface')),
            ],
            options={
                'db_table': 'RunLog',
            },
        ),
        migrations.CreateModel(
            name='RunStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('collection_pipeline_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_pipeline_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('run_log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.runlog')),
            ],
            options={
                'db_table': 'RunStepLog',
            },
        ),
    ]
