# Generated by Django 4.2.5 on 2023-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_runlog_runsteplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='execution_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='time_to_live',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
