# Generated by Django 4.2.5 on 2024-01-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolecollectionaccess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolecollectionaccess',
            name='id',
        ),
        migrations.AlterField(
            model_name='rolecollectionaccess',
            name='code',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
