# Generated by Django 4.2.5 on 2024-02-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_remove_role_id_alter_role_code'),
        ('collection', '0006_alter_collection_interfaceid'),
        ('rolecollectionaccess', '0002_remove_rolecollectionaccess_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecollectionaccess',
            name='RoleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.role'),
        ),
        migrations.AlterField(
            model_name='rolecollectionaccess',
            name='collectionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.collection'),
        ),
    ]
