# Generated by Django 4.2.5 on 2024-03-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_collection_executiontriggerrule_and_more'),
        ('role', '0003_alter_role_unique_together'),
        ('rolecollectionaccess', '0003_alter_rolecollectionaccess_roleid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolecollectionaccess',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='rolecollectionaccess',
            unique_together={('collectionId', 'RoleId')},
        ),
    ]
